# copy from https://github.com/archibate/vimrc/blob/nvim-2/dotfiles/.config/clangd/config.yaml
CompileFlags:
  Add:
    - --no-cuda-version-check
    - -Wno-unknown-warning-option
    - -D__clangd__  # add your custom flags
  Remove:
    - -forward-unknown-to-host-compiler
    - -expt-*
    - --expt-*
    - -gencode*
    - --generate-code*
    - -Xfatbin*
    - -arch=*
    - -rdc=*
    - -mno-*
InlayHints:
  ParameterNames: Yes
  DecucedTypes: Yes
