#----------------------------------------------------gereral--------------------------------------------------#
bind : command-prompt                         # enter command mode
bind R source-file ~/.config/tmux/tmux.conf   # update tmux's source file 


#----------------------------------------------------window---------------------------------------------------#
bind -n M-H previous-window                       # goto previous window
bind -n M-L next-window                           # goto next window
bind -n S-Left  previous-window
bind -n S-Right next-window
bind h split-window -h -c "#{pane_current_path}"  # horizontal window 
bind v split-window -v -c "#{pane_current_path}"  # vertical window
bind ^A last-window
bind w list-windows                           # list all windows
bind '"' choose-window                        # choose one window 
bind r command-prompt "rename-window %%"      # rename current window 


#-----------------------------------------------------pane-----------------------------------------------------#
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7
bind w swap-pane -D
bind z resize-pane -Z


#----------------------------------------------------session---------------------------------------------------# 
bind ^D detach                   # detach session      
bind S choose-session            # choose session


#----------------------------------------------------plugins---------------------------------------------------#


#----------------------------------------------------others----------------------------------------------------#
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -n C-q display-popup -w "90%" -h "85%" -E nvim

bind ^X lock-server
bind * list-clients
bind ^L refresh-client
bind l refresh-client

